import { VmSym } from '../../../as/assembly/dsp/vm-sym.ts'

export const builtinSyms: Record<string, number> = {
  out: VmSym.Out,
  solo: VmSym.Solo,
  post: VmSym.Post,
  sine: VmSym.Sine,
  tri: VmSym.Tri,
  saw: VmSym.Saw,
  ramp: VmSym.Ramp,
  sqr: VmSym.Sqr,
  pwm: VmSym.Pwm,
  phasor: VmSym.Phasor,
  ad: VmSym.Ad,
  adsr: VmSym.Adsr,
  envfollow: VmSym.Envfollow,
  mini: VmSym.Mini,
  analyser: VmSym.Analyser,
  compressor: VmSym.Compressor,
  expander: VmSym.Expander,
  gate: VmSym.Gate,
  limiter: VmSym.Limiter,
  t: VmSym.T,
  co: VmSym.Co,
  play: VmSym.Play,
  playPick: VmSym.PlayPick,
  timeline: VmSym.Timeline,
  sampler: VmSym.Sampler,
  slicer: VmSym.Slicer,
  every: VmSym.Every,
  at: VmSym.At,
  note: VmSym.Note,
  degree: VmSym.Degree,
  map: VmSym.Map,
  sum: VmSym.Sum,
  avg: VmSym.Avg,
  oversample: VmSym.Oversample,
  glide: VmSym.Glide,
  slew: VmSym.Slew,
  lp: VmSym.Lp,
  hp: VmSym.Hp,
  bp: VmSym.Bp,
  bs: VmSym.Bs,
  ls: VmSym.Ls,
  hs: VmSym.Hs,
  peak: VmSym.Peak,
  ap: VmSym.Ap,
  slp: VmSym.Slp,
  shp: VmSym.Shp,
  sbp: VmSym.Sbp,
  sbs: VmSym.Sbs,
  speak: VmSym.Speak,
  sap: VmSym.Sap,
  mlp: VmSym.Mlp,
  mhp: VmSym.Mhp,
  diodeladder: VmSym.DiodeLadder,
  olp: VmSym.Olp,
  ohp: VmSym.Ohp,
  k: VmSym.K,
  euclid: VmSym.Euclid,
  lfosine: VmSym.LfoSine,
  lfotri: VmSym.LfoTri,
  lfosaw: VmSym.LfoSaw,
  lforamp: VmSym.LfoRamp,
  lfosqr: VmSym.LfoSqr,
  lfosah: VmSym.LfoSah,
  white: VmSym.White,
  gauss: VmSym.Gauss,
  pink: VmSym.Pink,
  brown: VmSym.Brown,
  smooth: VmSym.Smooth,
  fractal: VmSym.Fractal,
  delay: VmSym.Delay,
  freeverb: VmSym.Freeverb,
  velvet: VmSym.Velvet,
  dattorro: VmSym.Dattorro,
  fdn: VmSym.Fdn,
  dc: VmSym.Dc,
  // Runtime directive globals (stable ids so VM can provide defaults)
  tune: VmSym.Tune,
  octave: VmSym.Octave,
  transpose: VmSym.Transpose,
  scale: VmSym.Scale,
  // Named args for out() and solo()
  L: VmSym.L,
  R: VmSym.R,
  // Named args for post()
  cb: VmSym.Cb,
  callback: VmSym.Cb,
  // Named args for adsr()
  attack: VmSym.Attack,
  decay: VmSym.Decay,
  sustain: VmSym.Sustain,
  release: VmSym.Release,
  trig: VmSym.Trig,
  // Named args for every()
  // NOTE: `bar` symbol id is shared with `at()`'s `bar` named arg.
  prob: VmSym.Prob,
  swing: VmSym.Swing,
  offset: VmSym.Offset,
  // Named args for pwm()
  width: VmSym.Width,
  seed: VmSym.Seed,
  // Named args for at()
  bar: VmSym.Bar,
  // NOTE: `every` key for at() reuses the builtin `every` symbol id (12).
  // Named args for lp()
  cutoff: VmSym.Cut,
  q: VmSym.Q,
  in: VmSym.In,
  // Named args for slew()
  up: VmSym.Up,
  down: VmSym.Down,
  exponent: VmSym.Exponent,
  // Named args for sampler() and slicer()
  speed: VmSym.Speed,
  repeat: VmSym.Repeat,
  slice: VmSym.Slice,
  threshold: VmSym.Threshold,
  ratio: VmSym.Ratio,
  knee: VmSym.Knee,
  hold: VmSym.Hold,
  gain: VmSym.Gain,
  // Named args for analyser()
  index: VmSym.Index,
  // Named args for timeline()
  pattern: VmSym.Pattern,
  color: VmSym.Color,
  // Named args for sampler()
  sample: VmSym.Sample,
  // Named args for note()
  midi: VmSym.Midi,
  // Named args for analyser (alternative)
  signal: VmSym.Signal,
  key: VmSym.Key,
  // Named args for mini/play
  hz: VmSym.Hz,
  seq: VmSym.Seq,
  voices: VmSym.Voices,
  // Named args for smooth()/fractal()
  rate: VmSym.Rate,
  curve: VmSym.Curve,
  octaves: VmSym.Octaves,
  seconds: VmSym.Seconds,
  feedback: VmSym.Feedback,
  size: VmSym.Size,
  roomSize: VmSym.Roomsize,
  roomsize: VmSym.Roomsize,
  damping: VmSym.Damping,
  wet: VmSym.Wet,
  dry: VmSym.Dry,
  preDelay: VmSym.PreDelay,
  bandwidth: VmSym.Bandwidth,
  inputDiffusion1: VmSym.InputDiffusion1,
  inputDiffusion2: VmSym.InputDiffusion2,
  decayDiffusion1: VmSym.DecayDiffusion1,
  decayDiffusion2: VmSym.DecayDiffusion2,
  excursionRate: VmSym.ExcursionRate,
  excursionDepth: VmSym.ExcursionDepth,
  hfDecay: VmSym.HfDecay,
  modDepth: VmSym.ModDepth,
  // Math functions
  sin: VmSym.Sin,
  cos: VmSym.Cos,
  tan: VmSym.Tan,
  asin: VmSym.Asin,
  acos: VmSym.Acos,
  tanh: VmSym.Tanh,
  atan: VmSym.Atan,
  abs: VmSym.Abs,
  sqrt: VmSym.Sqrt,
  square: VmSym.Square,
  cube: VmSym.Cube,
  hypot: VmSym.Hypot,
  log: VmSym.Log,
  exp: VmSym.Exp,
  log10: VmSym.Log10,
  log2: VmSym.Log2,
  exp2: VmSym.Exp2,
  min: VmSym.Min,
  max: VmSym.Max,
  clamp: VmSym.Clamp,
  wrap: VmSym.Wrap,
  mod: VmSym.Mod,
  pingpong: VmSym.Pingpong,
  fold: VmSym.Fold,
  floor: VmSym.Floor,
  ceil: VmSym.Ceil,
  round: VmSym.Round,
  trunc: VmSym.Trunc,
  snap: VmSym.Snap,
  fract: VmSym.Fract,
  sign: VmSym.Sign,
  lerp: VmSym.Lerp,
  smoothstep: VmSym.Smoothstep,
  smootherstep: VmSym.Smootherstep,
  step: VmSym.Step,
  heaviside: VmSym.Heaviside,
  select: VmSym.Select,
  isnan: VmSym.Isnan,
  isinf: VmSym.Isinf,
  safediv: VmSym.Safediv,
  // Named args for math functions
  lo: VmSym.Lo,
  hi: VmSym.Hi,
  a: VmSym.A,
  b: VmSym.B,
  x: VmSym.X,
  y: VmSym.Y,
  edge: VmSym.Edge,
  edge0: VmSym.Edge0,
  edge1: VmSym.Edge1,
  cond: VmSym.Cond,
}
